[[ -s $HOME/.config/zsh/hooks/_loader.zsh ]] && HOOK_DIR="$HOME/.config/zsh/hooks/zshenv.d" source "$HOME/.config/zsh/hooks/_loader.zsh";
[[ -s "$HOME/.config/zsh/hooks/zshenv" ]] && source "$HOME/.config/zsh/hooks/zshenv"
