{
  ack = "nocorrect ack";
  cd = "nocorrect cd";
  cp = "nocorrect cp";
  ebuild = "nocorrect ebuild";
  fc = "noglob fc";
  find = "noglob find";
  ftp = "noglob ftp";
  gcc = "nocorrect gcc";
  gist = "nocorrect gist";
  grep = "noglob grep --color=auto";
  heroku = "nocorrect heroku";
  history = "noglob history";
  ln = "nocorrect ln";
  man = "sman";
  mkdir = "nocorrect mkdir";
  mv = "nocorrect mv";
  mysql = "nocorrect mysql";
  rm = "rm -i";
  rsync = "noglob rsync";
  scp = "noglob scp";
  sftp = "noglob sftp";

  cdb = ''cd "+1"'';
  cdr = ''cd "$(realpath . 2>/dev/null || pwd)"'';
  cat = "bat -p --pager=never";
  df = "df -kh";
  du = "du -kh";
  g = "git";
  grepb = "grep --line-buffered";
  k = "kubectl";
  l = "ls -1A";
  la = "ll -A";
  lc = "lt -c";
  lk = "ll -Sr";
  ll = "ls -lh";
  lm = ''la | "$PAGER"'';
  lr = "ll -R";
  ls = "eza --group-directories-first";
  lt = "ll -tr";
  lu = "lt -u";
  lx = "ll -XB";
  o = "open";
  oops = "sudo $(fc -ln -1)";
  topc = "top -o cpu";
  topm = "top -o vsize";
  tpaste = "tmux saveb - | pbpaste";
  tcopy = "tmux show-buffer | pbcopy";
}
