services:
  devsuite:
    build:
      context: .
      dockerfile: Containerfile
    image: dotfiles-nix-devsuite:latest
    container_name: dotfiles-nix-devsuite
    hostname: dotfiles-nix-devsuite
    volumes:
      - ../..:/workspace/dotfiles-nix:ro
