services:
  testsuite:
    build:
      context: .
      dockerfile: Containerfile
    image: dotfiles-nix-test-suite:latest
    container_name: dotfiles-nix-test-suite
    hostname: dotfiles-nix-test-suite
    environment:
      DOTFILES_NIX_HOME_FLAKE: ${DOTFILES_NIX_HOME_FLAKE:-path:/workspace/dotfiles-nix}
      DOTFILES_NIX_HOME_PROFILE: ${DOTFILES_NIX_HOME_PROFILE:-testuser@integration-test-suite}
    volumes:
      - ../..:/workspace/dotfiles-nix:ro
